# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080
    servlet:
        context-path: /springbootvtgh9

spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://123.207.83.138:15433/ental_health_system
        username: postgres
        password: huangxi
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
    resources:
      static-locations: classpath:static/,file:static/
# 删除或注释掉 springdoc 相关配置
# 在现有配置基础上添加
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API docs
  packages-to-scan: com.controller
  paths-to-match: /**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
#   paths-to-match: /**
  
#mybatis
# MyBatis-Plus configuration
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: input
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
